# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b4e681c2-7eb1-41ae-a1e4-5157ebd18732";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-efbc809f-e9c0-49d6-bcf5-72f5d2587c8c".device = "/dev/disk/by-uuid/efbc809f-e9c0-49d6-bcf5-72f5d2587c8c";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A466-F423";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/c1407f13-1e5a-449c-8645-4babf6813b14"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp46s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # added 20250504
  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs;[
      vpl-gpu-rt
    ];
  };
  # hardware.system76.enableAll = true;
}
